version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.7.4
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: Install-npm
          command: npm install
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm run test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
      - run:
          name: Deploy to FTP
          command: node .circleci/deploy.js

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master